version: 2
jobs:
  build:

    docker:
      - image: circleci/android:api-28

    working_directory: ~/AndroidStudioProjects/CircleCI

    environment:
      JVM_OPTS: -Xmx3200m

    steps:

      #Checkout the codebase
      - checkout

      # Gradle sync Cache - Dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # Approve Android Studio SDK Licenses
      - run:
          name: Approve license for build tools
          command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      #Permissions for Gradle
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew

#      #Gradle Sync
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      #Save Cache for future builds
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      #Run all unit tests
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results